# Array basic using numpy

In [ ]:
import numpy as np

In [ ]:
l1=[1,2,3,4]

In [ ]:
arr=np.array(l1)

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
l2=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
print(l2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
arr=np.array(l2)

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#using built function

In [ ]:
# arrange method

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# all zeros

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#all ones

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#linspace method

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# array of random number  (uniform distribution between 0 to 1)

In [ ]:
np.random.rand(4,4)

array([[0.78926902, 0.73073103, 0.38710985, 0.90363013],
       [0.91937426, 0.38392692, 0.55145863, 0.75792201],
       [0.67757259, 0.17499929, 0.7479393 , 0.41187138],
       [0.10414322, 0.57005176, 0.56785324, 0.4385531 ]])

In [ ]:
#standard normal distribution or gaussian distribution

In [ ]:
np.random.randn(4,4)

array([[-0.15674358, -0.17514162, -1.15659952,  0.72205478],
       [-0.2939029 , -0.90308871, -1.22841839,  0.35298825],
       [ 1.64537646,  1.08280226,  0.1108605 ,  0.40926113],
       [ 1.61212089, -1.25425349,  1.54735078,  0.06580693]])

In [ ]:
#random integer 

In [ ]:
np.random.randint(1,11,10)

array([ 6,  7, 10,  7,  6,  9,  7,  9,  7,  5])

In [ ]:
arr=np.arange(10)

In [ ]:
len(arr)

10

In [ ]:
# reshape
arr.reshape(len(arr),1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
randarr=np.random.randint(1,100,25)

In [ ]:
print(randarr)

[71 65 37 27 76 92 25 66 71 72 32 10 69 16 71 51 25 78 66 96 26 56 98 15
 57]


In [ ]:
randarr.max()

98

In [ ]:
randarr.argmax() #gives the poistion where max is.

22

In [ ]:
b=randarr.reshape(5,5)

In [ ]:
b.shape

(5, 5)

In [ ]:
# dtyper
b.dtype

dtype('int64')

In [ ]:
#broadcasting 

In [ ]:
arr=np.arange(10,20)

In [ ]:
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr[0:5]=5

In [ ]:
print(arr)

[ 5  5  5  5  5 15 16 17 18 19]


In [ ]:
slice_arr=arr[0:5]

In [ ]:
print(slice_arr)

[5 5 5 5 5]


In [ ]:
slice_arr[:]=12

In [ ]:
print(slice_arr)

[12 12 12 12 12]


In [ ]:
print(arr) #refrences type to save memory 

[12 12 12 12 12 15 16 17 18 19]


In [ ]:
# make copy to avoid refrences type
sl_copy=arr.copy()

In [ ]:
print(sl_copy)

[12 12 12 12 12 15 16 17 18 19]


In [ ]:
sl_copy[:]=99

In [ ]:
print(sl_copy)

[99 99 99 99 99 99 99 99 99 99]


In [ ]:
print(arr)

[12 12 12 12 12 15 16 17 18 19]


# Indexing 2d array 

In [ ]:
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [ ]:
print(arr_2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
arr_2d[0,0]

10

In [ ]:
arr_2d[1,2]

60

In [ ]:
arr_2d[0:,1:]


array([[20, 30],
       [50, 60],
       [80, 90]])

#Conditional selection

In [ ]:
arr=np.arange(1,11)

In [ ]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b=arr[arr%2==0]

In [ ]:
print(b)

[ 2  4  6  8 10]
